; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:node32s]
;platform = espressif32
platform = espressif32@3.0.0
board = node32s
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	https://github.com/me-no-dev/AsyncTCP.git#master
	https://github.com/me-no-dev/ESPAsyncWebServer.git#master
	sstaub/NTP @ ~1.4
	jordancrubin/Watermeter @ ^1.0.8
	jordancrubin/Ballvalve @ ^1.1.1
	bblanchon/ArduinoJson @ ^6.19.2
	mathertel/LiquidCrystal_PCF8574@^1.3.0
	igorantolic/Ai Esp32 Rotary Encoder @ ^1.4
	xreef/PCF8575 library@^1.0.3
	a223d/detaBaseArduinoESP32 @ ^1.0.0